pipeline:
  build:
    image: golang
    commands:
      - go build
  kici/kcidocker:
    appenv: test
    repo: wanglei/justtest
    tag: latest
    file: Dockerfile
    insecure: false
    when:
      event: [push, pull_request, tag, deployment]
  kici/kciemail:
    appenv: test
    recipients:
      - 541004974@qq.com
    when:
      event: [push, pull_request, tag, deployment]
      status:  [ failure, success ]



