workspace:
  base: /go
  path: 
pipeline:
  clone:
    image: index.qiniu.com/kci/plugin_git 
    remote: https://github.com/u2takey/justtest.git
    path: /go/src/github.com/u2takey
  clone:
    image: index.qiniu.com/kci/plugin_git 
    remote: https://github.com/kirk-enterprise/slate.git
    path: /go/src/github.com/kirk-enterprise/slate
  build:
    image: index.qiniu.com/kci/golang:1.6
    commands:
      - go build
  index.qiniu.com/kci/plugin_docker:
    repo: wanglei/justtest
    tag: latest
    insecure: false
    storage_path: /cache/u2takey
    when:
      event: [push, pull_request, tag, deployment]
  index.qiniu.com/kci/plugin_email:
    recipients:
      - 541004974@qq.com
    when:
      event: [push, pull_request, tag, deployment]
      status:  [ failure, success ]




