pipeline:
  build:
    image: index.qbox.me/wanglei/golang
    commands:
      - go build
  index.qbox.me/library/plugin_kodo:
    bucket: "tumi"
    source: ./justtest
    target: data/
    delete: true
  index.qbox.me/library/plugin_docker:
    appenv: test
    repo: wanglei/justtest
    tag: latest
    file: Dockerfile
    insecure: false
    when:
      event: [push, pull_request, tag, deployment]
  index.qbox.me/library/plugin_email:
    appenv: test
    recipients:
      - 541004974@qq.com
    when:
      event: [push, pull_request, tag, deployment]
      status:  [ failure, success ]





