pipeline:
  build:
    image: index.qiniu.com/wanglei2/golang
    commands:
      - go build
  index.qiniu.com/kci/plugin_docker:
    appenv: test
    repo: wanglei/justtest
    tag: latest
    file: Dockerfile
    insecure: false
    storage_path: /kci_cache/u2takey
    mirror: http://e05f9689.m.daocloud.io
    when:
      event: [push, pull_request, tag, deployment]
  index.qiniu.com/kci/plugin_email:
    appenv: test
    recipients:
      - 541004974@qq.com
    when:
      event: [push, pull_request, tag, deployment]
      status:  [ failure, success ]

